In [1]:
import numpy as np

## Question 1

Yes, there is a difference in the data type of both the variables. One is a list whereas another one is a numpy n-dimensional array.

In [3]:
list_ = ['1','2','3','4','5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))

<class 'list'>
<class 'numpy.ndarray'>


## Question 2

In [4]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [5]:
array_list.dtype

dtype('<U1')

## Question 3

Yes, there is a difference in the datatype of the elements present in both the variables. One is String and another one is Integer.

In [6]:
array_list = np.array(object=list_,dtype=int)
array_list.dtype

dtype('int64')

In [7]:
array_list

array([1, 2, 3, 4, 5])

In [9]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [10]:
list_

['1', '2', '3', '4', '5']

## Question 4

shape = Tells us the number of rows and columns in the array.

size = Tells us the total number of elements present in the array.

In [11]:
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(object=num_list)

In [12]:
num_array.shape

(2, 3)

In [13]:
num_array.size

6

## Question 5

In [14]:
data = np.zeros((3,3))
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Question 6

In [15]:
data1 = np.eye(5,5)
data1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])